### ISSUE TITLE
Write API call documentation

### ISSUE THREAD

**Issue by chrisliii** [20001LastOrder/McGrill_App#25]

**Comment by preyansh98** [comment]
Routes to be covered for this sprint: 
[ { path: '/delivery', methods: [ 'GET' ] },
  { path: '/delivery/issue', methods: [ 'POST', 'PUT' ] },
  { path: '/campus', methods: [ 'GET' ] },
  { path: '/campus/issue', methods: [ 'POST', 'DELETE', 'PUT' ] },
  { path: '/user', methods: [ 'GET' ] },
  { path: '/user/login', methods: [ 'GET' ] },
  { path: '/user/signup', methods: [ 'POST' ] } ]

**Comment by chrisliii** [comment]
Can I close this issue? @preyansh98
