### ISSUE TITLE
Add menu items API (finish by Feb. 11)

### ISSUE THREAD

**Issue by chrisliii** [20001LastOrder/McGrill_App#55]

**Comment by preyansh98** [comment]
Hi @chrisliii, @wzxiaa 

I have a couple of questions about this one. The menu items are not embedded internally within the restaurant in the model, just defined as a field. 

For the Add Menu Items API, would it then be sufficient to only post the menu item into the db? 
Or do I have to query the restaurant the item refers to and update the restaurant to include this menu item? I'm not sure how the reference between Restaurant and MenuItem is getting updated. 

The branch is called `preyansh98_menuitem_api` if you need it for reference. Thank you!

**Comment by 20001LastOrder** [comment]
> Hi @chrisliii, @wzxiaa
> 
> I have a couple of questions about this one. The menu items are not embedded internally within the restaurant in the model, just defined as a field.
> 
> For the Add Menu Items API, would it then be sufficient to only post the menu item into the db?
> Or do I have to query the restaurant the item refers to and update the restaurant to include this menu item? I'm not sure how the reference between Restaurant and MenuItem is getting updated.
> 
> The branch is called `preyansh98_menuitem_api` if you need it for reference. Thank you!

I think what is normal to do is to first post the menu item do the db, and then add the menu item to the restaurant which requires to add the menu item.

**Comment by preyansh98** [comment]
@20001LastOrder that makes sense. 

Do you think we should have frontend initiate two separate calls (1 - to post menu item) then (2 - add to the restaurant) ? Or should the backend chain both in create menu item api?

**Comment by 20001LastOrder** [comment]
> @20001LastOrder that makes sense.
> 
> Do you think we should have frontend initiate two separate calls (1 - to post menu item) then (2 - add to the restaurant) ? Or should the backend chain both in create menu item api?

What I think is that the user login as a restaurant and then add a menu item to that specific restaurant. So probably the backend should chain both.
